spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flexisaf
    username: postgres
    password: 1234
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        format_sql: true