spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flexisaf
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


jwt:
  expiration:
    time: 1800000

  public:
    key: classpath:certs/public.pem

  private:
    key: classpath:certs/private.pem